### ISSUE TITLE
failed to resolve @formkit/addons

### ISSUE THREAD

**Issue by omgzsa** [formkit/formkit#1030]
### Reproduction

https://formkit.com/playground?fkv=next&fileTab=formkit.config.js&css-framework=genesis&files=jc%5BTPVd.vueQ%3Cscrip2setup4D+ESM+Zt6ar8suppBNH_URL6%7Bhttps%3ADcdn...%7D-DW6wellW6secondary+pVHfiX6%7B.%2FOtherFiX.vue%7D.-Gscript4-%3Cq0%3CFBmKitz0typeYNxt7z0labelYFBmKi2Input7z0helpYedi2m8to+ge2starNd7z%2F4Gq-%3Cstyl8scoped4%2F*-vanilla+CSS+can+go+here.-Keep+styX6scopeHtoWvoiHmultipl8fiXs-overwriting+each+other+in+th8render+output.-*%2F-GstyX4%279%2CTfBmkit.c5.jsQZ2%28A1vue%22JZ2%28+31addons%22J-cons2c5+%3DA%7B%28zplugins%3A+%5B3%7B%7D%5D%2Cztheme%3A+%22genesis%22%2C-%29%7DJ-expB2defaul2c5J%27%7EremovabX%21true%7EsiXnt%21false9%5D-%5Cn0++1+%29+_%22%40fBmkit%2F2t+3creaNMultiSNpPlugin4%3E-5onfig6s+7%5C%278e+9%7Eadded%21true%29A+defaultC5BorD%2F%2FG%3C%2FHd+J%3B-NteQ%27%7EeditB%21%27T%28%27name%21%27VlaygrounW+aXleY%3D7ZimpB_from+qNmplaN4z-0%01zq_ZYXWVTQNJHGDBA9876543210-_

### Describe the bug

The problem is obviously not reproducable on the playground since all your plugins and addons work there.

Documentation says:
"FormKit ships with a first-party multi-step input plugin available from the @formkit/addons package..."

I have a nuxt 3 project in which I have a formkit.config.js file for configuration.

nuxt.config.js:
```
export default defineNuxtConfig({
  modules: [
    '@formkit/nuxt',
  ],
  formkit: {
    configFile: './formkit.config.js',
 },
```
formkit.config.js:
```
import { defaultConfig } from '@formkit/vue';
import { createMultiStepPlugin } from '@formkit/addons';

const config = defaultConfig({
  plugins: [createMultiStepPlugin()],
  theme: 'genesis',
});

export default config;
```

Expected behaviour is that it works. But for some reason it doesn't and the error log looks like this:

```
[7:21:41 PM]  ERROR  Failed to resolve import "@formkit/addons" from "formkit.config.js". Does the file exist?


[7:21:42 PM]  ERROR  Internal server error: Failed to resolve import "@formkit/addons" from "formkit.config.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/zs3ll0/projects/acst-shop/formkit.config.js:2:40
  1  |  import { defaultConfig } from '@formkit/vue';
  2  |  import { createMultiStepPlugin } from '@formkit/addons';
     |                                         ^
  3  |  
  4  |  const config = defaultConfig({
      at formatError (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:43993:46)
      at TransformContext.error (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:43989:19)
      at normalizeUrl (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:41801:33)
      at async file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:41945:47
      at async Promise.all (index 1)
      at async TransformContext.transform (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:41870:13)
      at async Object.transform (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:44283:30)
      at async loadAndTransform (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:54950:29)
      at async viteTransformMiddleware (file:///home/zs3ll0/projects/acst-shop/node_modules/vite/dist/node/chunks/dep-df561101.js:64345:32)

[Vue Router warn]: No match found for location with path "/_nuxt/formkit.config.js?t=1699640501130"
[Vue Router warn]: No match found for location with path "/_nuxt/formkit.config.js?t=1699640501130"
[Vue Router warn]: No match found for location with path "/_nuxt/formkit.config.js?t=1699640501130"
[Vue Router warn]: No match found for location with path "/_nuxt/formkit.config.js"
[nuxt] Could not resolve id @formkit/addons /home/zs3ll0/projects/acst-shop/formkit.config.js    7:21:41 PM
```

I also don't see it exposed in my IDE. Anyone has a clear idea on whats happening here?

![addons-issue](https://github.com/formkit/formkit/assets/58146330/5714e035-c837-4ed9-be78-13db52369250)

Thank you.

### Environment

• OS: Win 10
• Node 18+
• Nuxt 3.6.5
• FormKit 1.3

**Comment by GustavoFenilli** [comment]
You need to actually install, it comes with first party addons but it is not installed by default. so just run `npm install @formkit/addons`.

**Comment by GustavoFenilli** [comment]
Reopening as this might be a good addition to the docs as a step that `@formkit/addons` needs to be installed and its not available by default.

**Comment by justin-schroeder** [comment]
Good point @fenilli — do you mind adding this to the docs for the various addons pages?
