### ISSUE TITLE
Certain combinations of conditions throw errors on user input

### ISSUE THREAD

**Issue by SDRACK** [formkit/formkit#1037]
### Reproduction

https://formkit.link/62233265ee7870019b392907233c397d

### Describe the bug

Hey all 👋 

The linked playground demos this best, based on a trimmed down example of a form we're building. 

I've not been able to isolate the conditions to cause this precisely, but on occasions (such as in the playground), adding conditions to schema elements causes errors when form data changes.

To reproduce in my example, select 'Yes' on the field 'CCC'. The UI will break and this error will be thrown:

<img width="473" alt="Screenshot 2023-11-20 at 14 08 29" src="https://github.com/formkit/formkit/assets/8395303/f1477f00-bacc-442a-824d-7137ad0f114a">

```
index.mjs:132 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at normalizeOptions (index.mjs:132:47)
    at index.mjs:194:65
    at Function.r [as dispatch] (index.mjs:27:48)
    at Object.set (index.mjs:2284:17)
    at index.mjs:1245:35
    at callWithErrorHandling (vue.esm-browser.js:1615:18)
    at callWithAsyncErrorHandling (vue.esm-browser.js:1623:17)
    at g (vue.esm-browser.js:3252:9)
    at flushPreFlushCbs (vue.esm-browser.js:1764:7)
```

(Apologies in advance for the bloated playground - when trimmed down any more, the issue vanishes.)

There's a 'fix' of sorts - putting a `key` on some of the fields involved seems to somewhat mitigate the issue, but it doesn't seem a perfect solution. (See the commented out lines.)

Any input much appreciated :) Thanks in advance.

### Environment

• OS: Ventura 13.5.1
• Browser Chrome Version 119.0.6045.159
• Version Formkit 1.3

**Comment by SDRACK** [comment]
Aha - that's great, thanks @justin-schroeder, appreciate the answer! Hadn't clocked that in the docs, so pretty happy I stumbled upon the `key` approach independently.

Would adding a `key` to conditional fields be something that might be baked into Formkit at some point? Perhaps in a similar manner to how the `id` attribute is handled (i.e. use a defined ID if present, otherwise Formkit generates one)?

It's acting as a bit of a 'gotcha' for our team and has caught us out a few times - I suppose we're so used to adding keys to loops in Vue it's second nature, but less so when applying here :)
