### ISSUE TITLE
Schema with field’s dependences failed to generate with condition value equals to select initial value

### ISSUE THREAD

**Issue by lct005** [formkit/formkit#521]
### Reproduction

https://formkit.link/ead4fdd64430f3a7f726d405a7e4f0e8

### Describe the bug

When there are multiple field dependencies (with more than 3 pairs) loading with condition value equals to option first initial value, then it is failed to display the dependent fields.

![image](https://user-images.githubusercontent.com/4641151/210729217-ee0f94be-5020-4e50-8642-4190cdabd7c1.png)

Error console log:
`
index.mjs:57 
    Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at normalizeOptions (index.mjs:57:19)
    at index.mjs:105:30
    at Function.n [as dispatch] (index.mjs:15:20)
    at Object.set (index.mjs:1857:52)
    at index.mjs:1199:28
    at callWithErrorHandling (vue.esm-browser.js:1741:22)
    at callWithAsyncErrorHandling (vue.esm-browser.js:1750:21)
    at job (vue.esm-browser.js:3345:17)
    at flushPreFlushCbs (vue.esm-browser.js:1900:13)
`

`
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (vue.esm-browser.js:2669:29)
    at updateComponent (vue.esm-browser.js:7037:13)
    at processComponent (vue.esm-browser.js:6991:13)
    at patch (vue.esm-browser.js:6591:21)
    at patchKeyedChildren (vue.esm-browser.js:7369:17)
    at patchChildren (vue.esm-browser.js:7296:21)
    at processFragment (vue.esm-browser.js:6976:17)
    at patch (vue.esm-browser.js:6584:17)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7199:17)
    at ReactiveEffect.run (vue.esm-browser.js:616:25)
`

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by GustavoFenilli** [comment]
You forgot to add those variables to the `data` so it was always undefined. https://formkit.link/032ced7a8f92957ec98321ba8965e970
