### ISSUE TITLE
Use Nuxt with TailwindCSS in formkit.config.ts

### ISSUE THREAD

**Issue by bushbill** [formkit/formkit#64]
Hi,

someone has an example to use the TailwindCSS config (here: https://formkit.com/essentials/styling#tailwind-css-example) made for "vue" package in a "nuxt3" project?

I miss an example to use the "formkit.config.ts" in a "nuxt3" project. I have no idea how to use this:-(

Thank you.

**Comment by bushbill** [comment]
@andrew-boyd Thank you.

But if I include this config above into formit.config.js I got the following error after running "yarn dev -o":

```
ERROR  [worker] Cannot read properties of undefined (reading 'split')                                                                                                                                                                                                                                           08:14:52

  at createClassObject (.nuxt/dist/server/server.mjs:11768:22)
  at Proxy.rootClasses (.nuxt/dist/server/server.mjs:11777:16)
  at .nuxt/dist/server/server.mjs:3816:43
  at watch (.nuxt/dist/server/server.mjs:9131:17)
  at Proxy.<anonymous> (.nuxt/dist/server/server.mjs:9046:39)
  at Object.get (.nuxt/dist/server/server.mjs:3814:34)
  at Reflect.get (<anonymous>)
  at Object.get (node_modules/@vue/reactivity/dist/reactivity.cjs.js:428:29)
  at .nuxt/dist/server/server.mjs:2716:33
  at Array.reduce (<anonymous>)


 ERROR  [proxy] connect ENOENT /tmp/nitro/worker-28538-1.sock                                                                                                                                                                                                                                                    08:14:53

  at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
```

What could be wrong?

**Comment by justin-schroeder** [comment]
@bushbill the code example looks like its missing an undefined check:

Change this:

```js
function createClassObject (classesArray) {
  const classList = {}
  classesArray.split(' ').forEach(className => {
      classList[className] = true
  })
  return classList
}
```

To this:

```js
function createClassObject (classesArray) {
  const classList = {}
  if (typeof classesArray !== 'string') return classList
  classesArray.split(' ').forEach(className => {
      classList[className] = true
  })
  return classList
}
```

**Comment by andrew-boyd** [comment]
Thanks @justin-schroeder — I'll get this updated in the docs examples. Thought we'd already done that but they must not have made it out the door.
