### ISSUE TITLE
vitesse-formkit error when build

### ISSUE THREAD

**Issue by serggiocaramello** [formkit/formkit#71]
Hi, developer mode works as a charm, but, when i tried to make a build terminal shows this error: '@formkit/vue' does not provide an export named 'plugin'

Minimal reproduction: https://github.com/serggiocaramello/vitesse-formkit-issue

Full error message:

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:8912) UnhandledPromiseRejectionWarning: file:///C:/folder/vitesse-formkit/.vite-ssg-temp/main.mjs:20
import { plugin, defaultConfig } from "@formkit/vue";
         ^^^^^^
SyntaxError: The requested module '@formkit/vue' does not provide an export named 'plugin'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:124:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:179:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async build (C:\folder\vitesse-formkit\node_modules\.pnpm\vite-ssg@0.17.10_1ede6668370ad42aad1df87e2fa73e29\node_modules\vite-ssg\dist\node\cli.cjs:180:87)
    at async Object.handler (C:\folder\vitesse-formkit\node_modules\.pnpm\vite-ssg@0.17.10_1ede6668370ad42aad1df87e2fa73e29\node_modules\vite-ssg\dist\node\cli.cjs:314:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Desktop
-     OS: Windows 10 Pro 21 H1
-     Browser: Firefox 97.0

**Comment by justin-schroeder** [comment]
I'm able to reproduce this — although we are using a straight up the middle ESM/CJS so im not sure why this would be an issue for vite-ssg. Will investigate further.

**Comment by justin-schroeder** [comment]
Ok — I was able to track this down, and it is fixed in the beta.3 branch. The issue has to do with export maps in the package.json.

**Comment by serggiocaramello** [comment]
Nice!, Thank you for your help Justin.

**Comment by shadow81627** [comment]
I have a similar issue using formkit with [antfu/vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3). `"@formkit/nuxt": "1.0.0-beta.2"`

I get the below error in production (`yarn run start`).
```
The requested module '@formkit/vue' does not provide an export named 'defaultConfig'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)  
  at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)  
  at async Promise.all (index 0)  
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)  
  at async file://./.output/server/chunks/app/render.mjs:527:24  
  at async renderMiddleware (file://./.output/server/chunks/app/render.mjs:576:20)  
  at async handle (file://./.output/server/node_modules/h3/dist/index.mjs:601:19)
 ```

**Comment by justin-schroeder** [comment]
@shadow81627 this is also resolved in beta.3 🚀
