### ISSUE TITLE
Using conditionals in multi-step schema forms causes t.props is null

### ISSUE THREAD

**Issue by garbit** [formkit/formkit#823]
### Reproduction

https://formkit.link/2c1e38ed2ec9dfa979ebadadd090458b

### Describe the bug

When creating a multi-step form using a schema and a conditional on a step to show/hide the step I receive an error "t.props is null" (looks like the tab rendering part of the library).

Demo:
[https://formkit.link/2c1e38ed2ec9dfa979ebadadd090458b](https://formkit.link/2c1e38ed2ec9dfa979ebadadd090458b)

```
<script setup>
const schema = [
  {
    "$formkit": "multi-step",
    "tab-style": "progress",
    "valid-step-icon": "check",
    "allow-incomplete": true,
    "children": [
      {
        "$formkit": "step",
        "name": "contact",
        "children": [
          {
            "$formkit": "text",
            "id": "last_name",
            "name": "last_name",
            "label": "Nom",
            "validation": "required"
          },
          {
            "$formkit": "text",
            "name": "first_name",
            "label": "Prénom",
            "validation": "required"
          },
        ]
      },
      {
        "$formkit": "step",
        "name": "address",
        if: "$get(last_name).value == 'test'",
        "children": [
          {
            "$formkit": "text",
            "name": "address",
            "label": "Adresse"
          },
          {
            "$formkit": "text",
            "name": "postal_code",
            "label": "Code postal",
          },
          {
            "$formkit": "text",
            "name": "city",
            "label": "Ville",
          }
        ],
        // use sectionsSchema to override default markup in schema.
        "sectionsSchema": {
          "stepNext": {
            "if": 'true', // forcibly enable to override default schema conditonal.
            "children": [
              {
                "$formkit": "submit"
              }
            ]
          }
        }
      }
    ],
  },
]
</script>

<template>
  <FormKitSchema :schema="schema" />
</template>
```

### Environment

• OS: MacOS
• Browser: Firefox
• Version: 115.0.1

**Comment by andrew-boyd** [comment]
This will be fixed in beta.18

https://formkit.link/4be637be3de2076de85d1a2120493e24

**Comment by garbit** [comment]
Awesome!

Weirdly I can't get the same code in the playground to work using "@formkit/nuxt": "0.18.0-23c4d8f". I get the following error: 
![image](https://github.com/formkit/formkit/assets/555396/3dc6113d-13b0-405b-a6d4-189801095462)

**Comment by garbit** [comment]
I still seem to have this issue using:

```
"@formkit/nuxt": "0.18.0-23c4d8f",
"@formkit/vue": "0.18.0-23c4d8f",
```

Is this a nuxt specific issue?

**Comment by andrew-boyd** [comment]
You’re using a version published at a specific commit (hence the hash in the version number). Does the issue persist if you use the latest release `0.17.5`?

**Comment by garbit** [comment]
I installed previously using @latest but I've installed the following:

```
"@formkit/vue": "0.17.5",
"@formkit/nuxt": "0.17.5",
```

Debug console
```
Uncaught (in promise) TypeError: tab2.props is null
```


Nuxt error message
```
500

Cannot read properties of null (reading 'label')

at Array.map ()
at createSSRStepsFromTabs (./node_modules/.pnpm/@formkit+addons@0.17.4/node_modules/@formkit/addons/dist/index.mjs:632:34)
at multiStepPlugin (./node_modules/.pnpm/@formkit+addons@0.17.4/node_modules/@formkit/addons/dist/index.mjs:671:37)
at use (./node_modules/.pnpm/@formkit+core@0.17.4/node_modules/@formkit/core/dist/index.mjs:1844:20)
at nodeInit (./node_modules/.pnpm/@formkit+core@0.17.4/node_modules/@formkit/core/dist/index.mjs:2389:13)
at Module.createNode (./node_modules/.pnpm/@formkit+core@0.17.4/node_modules/@formkit/core/dist/index.mjs:2496:12)
at useInput (./node_modules/.pnpm/@formkit+vue@0.17.5_tailwindcss@3.3.2_vue@3.3.4/node_modules/@formkit/vue/dist/index.mjs:1198:40)
at setup (./node_modules/.pnpm/@formkit+vue@0.17.5_tailwindcss@3.3.2_vue@3.3.4/node_modules/@formkit/vue/dist/index.mjs:882:22)
at callWithErrorHandling (./node_modules/.pnpm/@vue+runtime-core@3.3.4/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
```

It looks like the same issue.

**Comment by garbit** [comment]
@andrew-boyd - update on this. I started to create an example project to demonstrate the issue however I've realised that I also need to use: `"@formkit/addons": "^0.17.5"` 🤦 

It looks like everything is working - apologies for any inconvenience. Thank you for your swift responses.

**Comment by andrew-boyd** [comment]
No problem at all! Glad it’s sorted.
