### ISSUE TITLE
formkit/nuxt@>1.2.0 results in a "register is not a function" error on page load

### ISSUE THREAD

**Issue by kswzr** [formkit/formkit#996]
### Reproduction

see #Reproduction section

### Describe the bug

When upgrading or installing `@formkit/nuxt` to a server-side rendered nuxt project, I get following error:

`[nuxt] [request error] [unhandled] [500] __vite_ssr_import_9__.register is not a function
  at Module.defaultConfig (./node_modules/@formkit/vue/dist/index.mjs:2106:27)  
  at ./virtual:nuxt:/project-dir/.nuxt/formkitPlugin.mjs:12:46  
  at ./node_modules/nuxt/dist/app/nuxt.js:114:60  
  at fn (./node_modules/nuxt/dist/app/nuxt.js:162:44)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:68:55)  
  at ./node_modules/nuxt/dist/app/nuxt.js:164:56  
  at Object.runWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3855:18)  
  at callWithNuxt (./node_modules/nuxt/dist/app/nuxt.js:164:24)  
  at Object.runWithContext (./node_modules/nuxt/dist/app/nuxt.js:34:29)  
  at applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:114:39)`

## Reproduction
Currently I tried to reproduce it in a new project, but it feels like it has to do with SSR.

When the error page is rendered, and I click on a client-side redirect link, everything works good.

## Solution
When I remove line
* node_modules/@formkit/vue/dist/index.mjs:2089
* node_modules/@formkit/vue/dist/index.cjs:2109
* node_modules/@formkit/vue/dist/formkit-vue.js:10167

The problem does not occur anymore.

### Environment

• OS: macOS
• Browser Chrome
• Version any
* FormKit package: formkit/nuxt
* Affected versions: 1.2.0 - 1.2.2

**Comment by justin-schroeder** [comment]
Hmm. im unable to duplicate this issue. Anything else you can provide reproduction wise?
